#!/usr/bin/env bash

set -uexo pipefail
export AWS_PROFILE="${1?}"
BUCKET="${2?}"

list_object_versions() {
  aws s3api list-object-versions --bucket "$BUCKET" |
    jq '{Objects: [ ( .Versions[]? , .DeleteMarkers[]? ) | {Key:.Key, VersionId : .VersionId}], Quiet: false}'
}

aws s3api delete-objects --bucket "$BUCKET" --delete "$(list_object_versions)"
aws s3 rb --force s3://"$BUCKET"

