#!/bin/sh

: ${HOME:?}
INIT_DB="$HOME/workspace/random/test_db"

exec docker run --init -it --rm                               \
  -w /docker-entrypoint-initdb.d                              \
  -v "${INIT_DB:?}:/docker-entrypoint-initdb.d"               \
  -e MYSQL_DATABASE=directus                                  \
  -e MYSQL_ROOT_PASSWORD=password                             \
  -p 3306:3306                                                \
  mysql --default-authentication-plugin=mysql_native_password

  #--tmpfs /var/lib/mysql                                      \
