#!/usr/bin/env bash

docker ps -q  | xargs docker kill
docker ps -qa | xargs docker rm
docker run -d --rm -p 8080:8080 -e SWAGGER_JSON=/build/$(ls -1 build/swagger/ | head) -v $PWD/build/swagger:/build swaggerapi/swagger-ui 

while true; do
    sleep 0;
    if nc -z -w5 localhost 8080 > /dev/stderr; then
        break;
    fi;
    sleep 2;
done

while true; do
    sleep 0;
    if test -n "$(curl -sf localhost:8080)"; then
        break;
    fi;
    sleep 2;
done

open http://localhost:8080

